###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:

  app:
    build:
      context: Vapp
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    container_name: vapp
    volumes:
      - ./Vapp:/usr/src/app
      - /usr/src/Vapp/node_modules
    command: yarn serve
    environment:
      - CHOKIDAR_USEPOLLING=true # <---- this enables the hot reloading

  webserver:
    image: 'nginx:alpine'
    working_dir: /app
    volumes:
      - '.:/app'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '3000:80'
  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /app
    volumes:
      - '.:/app'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
  mysql:
    platform: linux/x86_64
    image: "mysql:8.0"
    container_name: mysql
    volumes:
      - data-db:/data/db
    environment:
      - MYSQL_ROOT_PASSWORD=Kas2104516
      - MYSQL_DATABASE=app_dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    ports:
      - "6001:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: Kas2104516
    restart: always
    ports:
      - 8081:80
volumes:
  data-db: